[build]
target = "x86_64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-openwrt-linux-musl-gcc"
# dynamic linking libc
rustflags = [
    "-C",
    "target-feature=-crt-static",
    "-C",
    "link-self-contained=no",
    "-L",
    "/home/vagrant/openwrt-sdk-21.02.0-rc4-x86-64_gcc-8.4.0_musl.Linux-x86_64/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc/lib",
]

[unstable]
build-std = ["panic_abort", "std"]
build-std-features = ["panic_immediate_abort"]
